name: Daily Speed Test

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0:00 运行
  workflow_dispatch:      # 支持手动触发

jobs:
  speedtest:
    name: Run Speed Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'
          cache: true

      - name: Build clash-speedtest
        run: go build -v -o clash-speedtest

      - name: Merge Sources
        run: python pymerge/merge_sources.py pymerge/sources.yaml merged_sources.yaml quiet

      - name: Run speed test
        id: speedtest
        run: ./clash-speedtest -c merged_sources.yaml -yaml pymerge/result.yml -csv output.csv -min-speed 10

      - name: Generate Final Config
        if: steps.speedtest.outcome == 'success'
        run: python pymerge/merge_template.py pymerge/result.yml pymerge/template.yaml output.yaml quiet

      - name: Commit and push result
        if: steps.speedtest.outcome == 'success'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin main
          git add output.yaml output.csv pymerge/result.yml
          git commit -m "update: 更新测速结果 $(date '+%Y-%m-%d')" || exit 0
          git push
