name: Daily Speed Test

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0:00 运行
  workflow_dispatch:      # 支持手动触发

jobs:
  speedtest:
    name: Run Speed Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'

      - name: Build clash-speedtest
        run: go build -v -o clash-speedtest

      - name: Run speed test
        id: speedtest
        run: ./clash-speedtest -c https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge_yaml.yml -output result.yml -min-speed 5

      - name: Commit and push result
        if: steps.speedtest.outcome == 'success'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin main
          git add result.yml
          git commit -m "update: 更新测速结果 $(date '+%Y-%m-%d')" || exit 0
          git push
